# Generated by Django 5.1.4 on 2025-07-03 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquiler', '0022_delete_reservainventario'),
        ('producto', '0012_alter_precioproducto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='alquiler.alquiler')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Reserva de Inventario',
                'verbose_name_plural': 'Reservas de Inventario',
                'unique_together': {('producto', 'alquiler')},
            },
        ),
    ]
