# Generated by Django 5.1.4 on 2025-07-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_empresa_logo'),
        ('inventario', '0001_initial'),
        ('producto', '0012_alter_precioproducto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0, help_text='Nivel mínimo recomendado para alertas')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('bloqueado', models.BooleanField(default=False, help_text='Si está activo, el producto no se puede usar')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='producto.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Inventario por Sucursal',
                'verbose_name_plural': 'Inventarios por Sucursal',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
        migrations.DeleteModel(
            name='ReservaInventario',
        ),
    ]
