# Generated by Django 5.1.4 on 2025-07-03 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0022_delete_reservainventario'),
        ('empresa', '0007_empresa_logo'),
        ('inventario', '0002_inventariosucursal_delete_reservainventario'),
        ('producto', '0012_alter_precioproducto_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('devolucion', 'Devolución'), ('ajuste', 'Ajuste manual')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Debe ser positiva. El tipo define si se suma o se resta.')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alquiler.alquiler')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados_por', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.sucursal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_actualizados_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
