# Generated by Django 5.1.4 on 2025-07-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario'),
        ('producto', '0012_alter_precioproducto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.movimientoinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Ítem de movimiento',
                'verbose_name_plural': 'Ítems de movimiento',
            },
        ),
    ]
