# Generated by Django 5.1.4 on 2025-07-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movimientoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='alquiler',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='cantidad',
        ),
    ]
