# Generated by Django 5.1.4 on 2025-07-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_movimientoinventario_alquiler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
    ]
