# Generated by Django 5.1.4 on 2025-07-04 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_cliente_documento'),
        ('inventario', '0006_remove_movimientoinventario_producto'),
        ('producto', '0012_alter_precioproducto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.proveedor'),
        ),
    ]
