# Generated by Django 5.1.4 on 2025-07-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0022_delete_reservainventario'),
        ('cliente', '0005_alter_cliente_documento'),
        ('empresa', '0007_empresa_logo'),
        ('inventario', '0008_movimientoinventario_estado'),
        ('producto', '0012_alter_precioproducto_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_reservada', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.BooleanField(default=False, help_text='Se marca como entregado cuando el producto se entregue')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='alquiler.alquiler')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='cliente.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='producto.producto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='empresa.sucursal')),
            ],
            options={
                'verbose_name': 'Reserva de Inventario',
                'verbose_name_plural': 'Reservas de Inventario',
                'unique_together': {('producto', 'alquiler')},
            },
        ),
    ]
