# Generated by Django 5.1.4 on 2025-07-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_reservainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariosucursal',
            name='total_historico',
            field=models.IntegerField(default=0),
        ),
    ]
