# Generated by Django 5.1.4 on 2025-04-07 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_sucursal'),
        ('producto', '0003_proveedor_alter_producto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresa.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nombre', 'empresa')},
        ),
    ]
