# Generated by Django 4.2 on 2025-04-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_remove_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='activo', max_length=20),
        ),
    ]
