# Generated by Django 5.1.4 on 2025-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_alter_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='iva_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de IVA aplicado al producto', max_digits=5),
        ),
    ]
