# Generated by Django 5.1.4 on 2025-05-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_precioproducto_delete_detalleproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='producto.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='PrecioProducto',
        ),
    ]
