# Generated by Django 5.1.4 on 2025-05-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_precioproducto_delete_detalleproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproducto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
