# Generated by Django 5.1.4 on 2025-04-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
