# Generated by Django 5.1.4 on 2025-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_empresa_ciudad_empresa_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
    ]
