# Generated by Django 5.1.4 on 2025-04-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
