# Generated by Django 4.2 on 2025-10-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_remove_persona_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
