# Generated by Django 5.2.7 on 2025-11-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_persona_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
