# Generated by Django 5.2.7 on 2025-11-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_persona_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='numero_documento',
        ),
    ]
