# Generated by Django 5.1.4 on 2025-05-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0001_initial'),
        ('empresa', '0006_sucursal_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='descuento',
            old_name='actualizado_en',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='descuento',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='modificado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
