# Generated by Django 5.1.4 on 2025-05-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuento', '0002_rename_creado_en_descuento_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='tipo',
            field=models.CharField(choices=[('oferta', 'Descuento por oferta'), ('convenio', 'Descuento aplicado por convenio empresarial')], max_length=20),
        ),
    ]
