# Generated by Django 5.1.4 on 2025-05-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
        ('producto', '0007_alter_producto_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_a_cobrar', models.PositiveIntegerField(default=1)),
                ('precio_dia', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('valor_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='alquiler.alquiler')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
