# Generated by Django 5.1.4 on 2025-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0002_alquileritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileritem',
            name='dias_a_cobrar',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
