# Generated by Django 5.1.4 on 2025-05-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0003_alter_alquileritem_dias_a_cobrar'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquileres', to='cliente.cliente'),
        ),
    ]
