# Generated by Django 5.1.4 on 2025-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0005_alquiler_descuento_porcentaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='descuento_porcentaje',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento general en % sobre el total del alquiler', max_digits=5),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento individual en % (ej. 10 para 10%)', max_digits=5),
        ),
    ]
