# Generated by Django 5.1.4 on 2025-05-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0006_remove_alquiler_descuento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileritem',
            name='precio_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
