# Generated by Django 5.1.4 on 2025-05-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0007_alquileritem_precio_iva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alquileritem',
            old_name='precio_iva',
            new_name='valor_iva',
        ),
    ]
