# Generated by Django 5.1.4 on 2025-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0008_rename_precio_iva_alquileritem_valor_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileritem',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
