# Generated by Django 5.1.4 on 2025-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0009_alquileritem_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileritem',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
