# Generated by Django 5.1.4 on 2025-05-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0011_alquiler_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileritem',
            name='valor_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
