# Generated by Django 5.1.4 on 2025-05-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0012_alter_alquileritem_valor_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cobro del alquiler', max_digits=10),
        ),
    ]
