# Generated by Django 5.1.4 on 2025-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0014_alquileritem_subtotal_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileritem',
            name='precio_dia',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
    ]
