# Generated by Django 5.1.4 on 2025-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0015_alter_alquileritem_precio_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileritem',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento individual en % (ej. 10 para 10%)', max_digits=10),
        ),
    ]
