# Generated by Django 5.1.4 on 2025-05-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0016_alter_alquileritem_descuento_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquileritem',
            name='precio_dia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
