# Generated by Django 5.1.4 on 2025-05-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0017_alter_alquileritem_precio_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_curso', 'En curso'), ('con_abono', 'Con abono'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
    ]
