# Generated by Django 5.1.4 on 2025-06-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0019_eventoalquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_curso', 'En curso'), ('con_abono', 'Con abono'), ('liquidado', 'Liquidado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
    ]
