# Generated by Django 5.1.4 on 2025-07-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0021_alter_alquiler_estado_reservainventario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservaInventario',
        ),
    ]
