# Generated by Django 5.2.8 on 2025-11-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0023_abonoalquiler_liquidacionalquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('cotizacion', 'Cotización'), ('borrador', 'Borrador'), ('reservado', 'Reservado'), ('despachado', 'Despachado'), ('liquidado', 'Liquidado'), ('anulado', 'Anulado')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventoalquiler',
            name='tipo',
            field=models.CharField(choices=[('estado', 'Cambio de estado'), ('salida', 'Entrega de productos'), ('devolucion', 'Devolución'), ('nota', 'Nota interna')], max_length=20),
        ),
    ]
