# Generated by Django 5.1.4 on 2025-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_empresa'),
        ('empresa', '0006_sucursal_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('documento', 'empresa')},
        ),
    ]
