# Generated by Django 4.2.20 on 2025-05-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
